export const QUOTES = [
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'The more that you read, the more things you will know.', author: 'Dr. Seuss' },
  { text: 'Education is the most powerful weapon you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'The beautiful thing about learning is that no one can take it away from you.', author: 'B.B. King' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'A reader lives a thousand lives before he dies.', author: 'George R.R. Martin' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Knowledge is power.', author: 'Francis Bacon' },
  { text: 'The roots of education are bitter, but the fruit is sweet.', author: 'Aristotle' },
  { text: 'Education is not the filling of a pail, but the lighting of a fire.', author: 'W.B. Yeats' },
  { text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch' },
  { text: 'Seek knowledge from the cradle to the grave.', author: 'Prophet Muhammad (PBUH)' },
  { text: 'He who knows himself knows his Lord.', author: 'Ibn Arabi' },
  { text: 'The ink of the scholar is more sacred than the blood of the martyr.', author: 'Islamic Proverb' },
  { text: 'Whoever travels a path seeking knowledge, Allah makes easy for him a path to Paradise.', author: 'Hadith' },
  { text: 'Read! In the name of your Lord who created.', author: 'Quran 96:1' },
  { text: 'Intelligence plus character — that is the goal of true education.', author: 'Martin Luther King Jr.' },
  { text: 'Wisdom is not a product of schooling, but of the lifelong attempt to acquire it.', author: 'Albert Einstein' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.', author: 'Stephen Hawking' },
  { text: 'Real learning gets to the heart of what it means to be human.', author: 'Peter Senge' },
  { text: 'Develop a passion for learning. If you do, you will never cease to grow.', author: 'Anthony J. D\'Angelo' },
  { text: 'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.', author: 'Brian Herbert' },
  { text: 'Study without desire spoils the memory, and it retains nothing that it takes in.', author: 'Leonardo da Vinci' },
  { text: 'An hour of contemplation is worth more than a year of worship without understanding.', author: 'Islamic Scholar' },
  { text: 'The pursuit of knowledge is a duty of every Muslim.', author: 'Hadith' },
  { text: 'He who does not know his past cannot make the best of his present and future.', author: 'Ibn Khaldun' },
  { text: 'The cure for boredom is curiosity. There is no cure for curiosity.', author: 'Dorothy Parker' },
  { text: 'Curiosity is the engine of achievement.', author: 'Ken Robinson' },
  { text: 'Wonder is the beginning of wisdom.', author: 'Socrates' },
  { text: 'I have no special talent. I am only passionately curious.', author: 'Albert Einstein' },
  { text: 'The function of education is to teach one to think intensively and critically.', author: 'Martin Luther King Jr.' },
  { text: 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.', author: 'Abraham Lincoln' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'Nothing in life is to be feared, it is only to be understood.', author: 'Marie Curie' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Do not wait to strike until the iron is hot, but make it hot by striking.', author: 'William Butler Yeats' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'Education is the key to unlocking the world, a passport to freedom.', author: 'Oprah Winfrey' },
  { text: 'The highest activity a human being can attain is learning for understanding.', author: 'Baruch Spinoza' },
  { text: 'A mind stretched by a new idea can never go back to its original dimensions.', author: 'Oliver Wendell Holmes' },
];

export function getDailyQuote() {
  const day = new Date().getDate() + new Date().getMonth() * 31;
  return QUOTES[day % QUOTES.length];
}
