/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Oxford (default light)
        oxford: {
          bg:      '#F5F0E8',
          bg2:     '#EDE8DC',
          bg3:     '#E2DBCC',
          card:    '#FAF7F2',
          card2:   '#F0EBE0',
          text:    '#1A1208',
          text2:   '#4A3F2F',
          text3:   '#7A6E5F',
          accent:  '#8B4513',
          accent2: '#C5813A',
          accent3: '#4A7C59',
          border:  '#C8BEA8',
          border2: '#D8CEB8',
        },
        // Night
        night: {
          bg:      '#0D0F1A',
          bg2:     '#141728',
          bg3:     '#1A1D35',
          card:    '#181B2E',
          card2:   '#1E2238',
          text:    '#E8ECF5',
          text2:   '#A0AACC',
          text3:   '#5A6480',
          accent:  '#7B8FD4',
          accent2: '#9BB0F0',
          accent3: '#5A8FA0',
          border:  '#2A2F4A',
          border2: '#323858',
        },
        // Garden
        garden: {
          bg:      '#EFF5EC',
          bg2:     '#E2EFDD',
          bg3:     '#D5E8CE',
          card:    '#F8FCF6',
          card2:   '#EDFAE8',
          text:    '#1A2A18',
          text2:   '#3A5A38',
          text3:   '#6A8A68',
          accent:  '#3A7A4A',
          accent2: '#5A9A5A',
          accent3: '#8AB040',
          border:  '#B8D8B0',
          border2: '#C8E8C0',
        },
        // Space
        space: {
          bg:      '#080C12',
          bg2:     '#0E1420',
          bg3:     '#141C2E',
          card:    '#0E1420',
          card2:   '#141C2E',
          text:    '#D0E8FF',
          text2:   '#7090B0',
          text3:   '#3A5070',
          accent:  '#00BFFF',
          accent2: '#40D0FF',
          accent3: '#80FF90',
          border:  '#1A2A3A',
          border2: '#203040',
        },
      },
      fontFamily: {
        display: ['Lora_600SemiBold'],
        'display-italic': ['Lora_600SemiBold_Italic'],
        body: ['CrimsonPro_400Regular'],
        'body-italic': ['CrimsonPro_400Regular_Italic'],
        'body-semi': ['CrimsonPro_600SemiBold'],
        mono: ['JetBrainsMono_400Regular'],
        'mono-medium': ['JetBrainsMono_500Medium'],
      },
      borderRadius: {
        xl: '14px',
        '2xl': '20px',
      },
    },
  },
  plugins: [],
};
